component: apigateway
name: apigwDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  region: ap-guangzhou
  protocols:
    - http
    - https
  serviceName: 'sls_apigw_test'
  environment: release
  endpoints:
    - path: /helloworld
      method: GET
      description: Demo for MOCK Mode.Can be used in such as wechat public platform background domain name verification... 
      enableCORS: FALSE
      serviceType: MOCK
      serviceMockReturnMessage: Hello There!
    - path: /
      protocol: HTTP
      method: GET
      apiName: index
      function:
        functionName: myRestAPI
      usagePlan:
        # usagePlanId: 'usagePlan-gulpv8oa'
        usagePlanName: 'slsgw_usageplan_index'
        usagePlanDesc: 'slsgw usage plan test'
        maxRequestNum: 1000
